export const PLAYWRIGHT_HOST = "127.0.0.1";
export const PLAYWRIGHT_FRONTEND_PORT = 3100;
export const PLAYWRIGHT_BACKEND_PORT = 8100;

export const PLAYWRIGHT_FRONTEND_URL = `http://${PLAYWRIGHT_HOST}:${PLAYWRIGHT_FRONTEND_PORT}`;
export const PLAYWRIGHT_API_URL = `http://${PLAYWRIGHT_HOST}:${PLAYWRIGHT_BACKEND_PORT}`;