"""Initial migration with OBR and KYC

Revision ID: d63efde21547
Revises: 
Create Date: 2026-03-24 13:34:52.507113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63efde21547'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('refund_requested',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('subtotal_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(), nullable=True))
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_orders_invoice_number'), ['invoice_number'], unique=True)

    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=True))
        batch_op.add_column(sa.Column('is_taxable', sa.Boolean(), nullable=True))
        batch_op.alter_column('price_per_kg',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('transaction_logs', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nif_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_tax_payer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('id_document_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kyc_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kyc_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('kyc_notes', sa.String(), nullable=True))
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_users_id_number'), ['id_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_kyc_status'), ['kyc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_nif_number'), ['nif_number'], unique=False)

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_nif_number'))
        batch_op.drop_index(batch_op.f('ix_users_kyc_status'))
        batch_op.drop_index(batch_op.f('ix_users_id_number'))
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('kyc_notes')
        batch_op.drop_column('kyc_reviewed_at')
        batch_op.drop_column('kyc_status')
        batch_op.drop_column('id_document_url')
        batch_op.drop_column('id_number')
        batch_op.drop_column('nationality')
        batch_op.drop_column('is_tax_payer')
        batch_op.drop_column('nif_number')

    with op.batch_alter_table('transaction_logs', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price_per_kg',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('is_taxable')
        batch_op.drop_column('vat_rate')

    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_invoice_number'))
        batch_op.alter_column('total_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('subtotal_price')
        batch_op.drop_column('vat_amount')

    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.alter_column('refund_requested',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
